<?xml version="1.0"?>
<robot name="slatol" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="L1" value="0.30" />
  <xacro:property name="L2" value="0.35" />
  <xacro:property name="L3" value="0.35" />
  <xacro:property name="base_size" value="0.3" />
  <xacro:property name="link_radius" value="0.03" />

  <material name="Red"><color rgba="0.8 0 0 1"/></material>
  <material name="Blue"><color rgba="0 0 0.8 1"/></material>
  <material name="Black"><color rgba="0 0 0 1"/></material>

  <link name="base_link">
    <visual><geometry><box size="${base_size} ${base_size} ${base_size}" /></geometry><material name="Red"/></visual>
    <collision><geometry><box size="${base_size} ${base_size} ${base_size}" /></geometry></collision>
    <inertial><mass value="5.0"/><inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0"/></inertial>
  </link>

  <joint name="hip_haa_joint" type="revolute">
    <parent link="base_link"/>
    <child link="abduction_link"/>
    <origin xyz="0 ${-base_size/2} 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-0.78" upper="0.78" effort="100.0" velocity="2.0"/>
  </joint>
  
  <link name="abduction_link">
    <visual><geometry><cylinder length="${link_radius}" radius="${link_radius}"/></geometry><material name="Blue"/></visual>
    <collision><geometry><cylinder length="${link_radius}" radius="${link_radius}"/></geometry></collision>
    <inertial><mass value="0.2"/><inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/></inertial>
  </link>

  <joint name="hip_hfe_joint" type="revolute">
    <parent link="abduction_link"/>
    <child link="thigh_link"/>
    <origin xyz="0 0 ${-base_size/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="100.0" velocity="2.0"/>
  </joint>
  
  <link name="thigh_link">
    <visual><geometry><cylinder length="${L2}" radius="${link_radius}"/></geometry><origin xyz="0 0 ${-L2/2}" rpy="0 0 0"/> <material name="Red"/></visual>
    <collision><geometry><cylinder length="${L2}" radius="${link_radius}"/></geometry><origin xyz="0 0 ${-L2/2}" rpy="0 0 0"/></collision>
    <inertial><mass value="1.0"/><inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/></inertial>
  </link>
  
  <joint name="knee_kfe_joint" type="revolute">
    <parent link="thigh_link"/>
    <child link="calf_link"/>
    <origin xyz="0 0 ${-L2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-2.0" upper="0.0" effort="100.0" velocity="2.0"/>
  </joint>
  
  <link name="calf_link">
    <visual><geometry><cylinder length="${L3}" radius="${link_radius}"/></geometry><origin xyz="0 0 ${-L3/2}" rpy="0 0 0"/><material name="Blue"/></visual>
    <collision><geometry><cylinder length="${L3}" radius="${link_radius}"/></geometry><origin xyz="0 0 ${-L3/2}" rpy="0 0 0"/></collision>
    <inertial><mass value="1.0"/><inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/></inertial>
  </link>

  <joint name="foot_fixed_joint" type="fixed">
    <parent link="calf_link"/>
    <child link="foot_link"/>
    <origin xyz="0 0 ${-L3}" rpy="0 0 0"/>
  </joint>
  
  <link name="foot_link">
     <visual><geometry><sphere radius="0.05"/></geometry><material name="Black"/></visual>
     <collision><geometry><sphere radius="0.05"/></geometry></collision>
     <inertial><mass value="0.1"/><inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/></inertial>
  </link>

  <ros2_control name="IgnitionSystem" type="system">
    <hardware>
      <plugin>ign_ros2_control/IgnitionSystem</plugin>
    </hardware>
    <joint name="hip_haa_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="hip_hfe_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="knee_kfe_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="ign_ros2_control-system" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <parameters>$(find slatol3d_description)/config/slatol_controllers.yaml</parameters>
    </plugin>
  </gazebo>
  
</robot>